### ISSUE TITLE
Documentation fot Posting with the access token

### ISSUE THREAD

**Issue by bsylvain** [intridea/omniauth-oauth2#104]
I am sorry too ask the question here but I had no anwser on SO.

I use omniauth-oauth2 to consume an API I created with doorkeeper. Until now I only used it to retrieve data. Now I want to post data, and I can't find any doc about how to attach params to a post request.
Here is how I try to post through my token  : 
`
access_token.post("/api/user/tickets/",{test: "test"})`

On the API side, I have a post call but without any params.

Where can I find documentation about how to use post ?

**Comment by tmilewski** [comment]
While there's some simple functionality through [rest-client](https://github.com/rest-client/rest-client) to support the OAuth flow, this gem is not meant to be used as an API client.

The intention is, for those implementing this gem, to take the provided access token and use a more full-featured API client to make the appropriate requests.
