### ISSUE TITLE
Find a better way to cooperate with 3rd party omniauth oauth2 provider gems

### ISSUE THREAD

**Issue by urkle** [intridea/omniauth-oauth2#105]
In reference to #81 that is now locked.   IF you look at the history of referenced issues on that issue you will notice that NO 3rd party providers are adjusting their gem (e.g. replacing the one function in EVERY GEM in order to work around the change added in 1.4.0).. instead everyone is simply pinning to an older version of omniauth-oauth2.  This practice is going to make this gem very hard to use going forward if I need to use a gem that only works with 1.4.0+ and then I have other gems that are "locked" to older ones.

With this I am left with two choices.

1) fork every single gem to fix it (we currently use about 10+ gems for different oauth providers)
2) simply copying the strategies into our local product and modifying them there and going "screw it " with working with the numerous providers.

Currently we are doing a mix of the two, plus we have a "monkey patch" that restores the old behavior so we can still benefit from other security updates in the omniauth-oauth2 gem.

This is a real concern and the developers of this gem should take a more active role in ensuring that the 3rd party gems that use this framework are designed correctly.  As the reality is this one change has made a significant negative impact on the usefulness of this gem.

**Comment by tmilewski** [comment]
Most of the gems that you're referencing have pretty open version requirements, which should not be the case. As such, you can require the specific version of `omniauth-oauth2` (1.3.1) in your Gemfile and it will use that one.

**Comment by urkle** [comment]
I don't want to lock it to 1.3.1 as then I don't gain any security fixes in the latest versions of this gem.   And the issue is I have several gems that are locking it to 1.3.1 or lower (e.g. omniauth-redbooth) of which I've been trying to get them to update it but have had no luck.  And scanning through the list of linked issues on PR #81 I found several other gems which did the same bad choice of locking to 1.3.1. 

Right now you are simply telling me that I should "accept" and old version of omniauth-oauth2 with all the security issues that may be in there that will be discovered in the future.
