### ISSUE TITLE
In production, authentication fails with no errors (possibly CSRF problem)

### ISSUE THREAD

**Issue by snitko** [intridea/omniauth-oauth2#79]
We have development, staging and production environments. Authentication works just fine in the first two, but fails in production where it simply redirects back to the `new_user_registration_path` after it returns from Github (we're using Github authentication). No error message (even in logs) is present.

Production has SSL enabled, but I disabled it to test if it was the problem - same results. It also looks like the `github()` action in `Users::OmniauthCallbacksController` never gets called even - I tried debugging by asking it to print stuff into the logfile - nothing.

Finally, the weird part is that when I later try to sign in normally through devise and an existing account, I see the error `Could not authenticate from Github because csrf detected.` in flash message. OR sometimes I get a circular redirect.

I don't really know why that happens, but it only happens in production, which is almost identical to staging.Any ideas would be of great help.

[![Synapsi bounty](https://synapsi.com/bb/c9/f0/f8/95/fb98ab9159f51fd0297e236d.png)](https://synapsi.com/questions/in-production-authentication-fails-with-no-errors-201508191041)

**Comment by jwg2s** [comment]
@snitko are you getting this error?
```
ERROR -- omniauth: (google) Authentication failure! csrf_detected: OmniAuth::Strategies::OAuth2::CallbackError, csrf_detected | CSRF detected
```

**Comment by snitko** [comment]
No, here's what I see in the logs:

    6580 I, [2015-08-19T22:39:12.882293 #4646]  INFO -- : Started GET "/users/sign_in" for 146.88.42.129 at 2015-08-19 22:39:12 -0400
    6581 I, [2015-08-19T22:39:12.884412 #4646]  INFO -- : Processing by Devise::SessionsController#new as HTML
    6582 I, [2015-08-19T22:39:12.888320 #4646]  INFO -- :   Rendered shared/_github_auth.html.haml (0.9ms)
    6583 I, [2015-08-19T22:39:12.901676 #4646]  INFO -- :   Rendered devise/sessions/new.html.haml within layouts/application (14.4ms)
    6584 I, [2015-08-19T22:39:12.905295 #4646]  INFO -- :   Rendered layouts/_favicons.html.haml (0.1ms)
    6585 I, [2015-08-19T22:39:12.905965 #4646]  INFO -- :   Rendered /var/www/mysite/production/shared/bundle/ruby/2.2.0/gems/frontend_notifier-0.1.5/app/views/shared/_frontend_notifier.html.haml (0.5ms)
    6586 I, [2015-08-19T22:39:12.907062 #4646]  INFO -- :   Rendered shared/_pre_load_images.html.haml (0.9ms)
    6587 I, [2015-08-19T22:39:12.908378 #4646]  INFO -- :   Rendered shared/_user_session.html.haml (0.3ms)
    6588 I, [2015-08-19T22:39:12.908484 #4646]  INFO -- :   Rendered layouts/_header.html.haml (1.3ms)
    6589 I, [2015-08-19T22:39:12.909038 #4646]  INFO -- :   Rendered shared/_email.html.erb (0.0ms)
    6590 I, [2015-08-19T22:39:12.909172 #4646]  INFO -- :   Rendered layouts/_footer.html.haml (0.5ms)
    6591 I, [2015-08-19T22:39:12.909478 #4646]  INFO -- :   Rendered shared/_google_analytics.html.erb (0.1ms)
    6592 I, [2015-08-19T22:39:12.909892 #4646]  INFO -- : Completed 200 OK in 25ms (Views: 23.3ms | ActiveRecord: 0.0ms)
    6593 I, [2015-08-19T22:39:14.762168 #4646]  INFO -- : Started GET "/users/auth/github" for 146.88.42.129 at 2015-08-19 22:39:14 -0400
    6594 I, [2015-08-19T22:39:16.187133 #4646]  INFO -- : Started GET "/users/auth/github/callback?code=0ee9afe185439e7a8bcb&state=a3cb99312615594a7572b0c43f4786f197fe98aba5086528" for 146.88.42.129 at 2015-08-19 22:      39:16 -0400
    6595 I, [2015-08-19T22:39:16.309962 #4646]  INFO -- : Processing by Users::OmniauthCallbacksController#github as HTML
    6596 I, [2015-08-19T22:39:16.310242 #4646]  INFO -- :   Parameters: {"code"=>"0ee9afe185439e7a8bcb", "state"=>"a3cb99312615594a7572b0c43f4786f197fe98aba5086528"}
    6597 I, [2015-08-19T22:39:16.605672 #4646]  INFO -- : Redirected to https://mysite.com/users/sign_up
    6598 I, [2015-08-19T22:39:16.606014 #4646]  INFO -- : Completed 302 Found in 296ms (ActiveRecord: 3.2ms)
    6599 I, [2015-08-19T22:39:16.918286 #4646]  INFO -- : Started GET "/users/sign_up" for 146.88.42.129 at 2015-08-19 22:39:16 -0400
    6600 I, [2015-08-19T22:39:16.920614 #4646]  INFO -- : Processing by Devise::RegistrationsController#new as HTML
    6601 I, [2015-08-19T22:39:16.924000 #4646]  INFO -- :   Rendered shared/_github_auth.html.haml (0.7ms)
    6602 I, [2015-08-19T22:39:16.937616 #4646]  INFO -- :   Rendered devise/registrations/new.html.haml within layouts/application (14.5ms)
    6603 I, [2015-08-19T22:39:16.941252 #4646]  INFO -- :   Rendered layouts/_favicons.html.haml (0.1ms)
    6604 I, [2015-08-19T22:39:16.941999 #4646]  INFO -- :   Rendered /var/www/mysite/production/shared/bundle/ruby/2.2.0/gems/frontend_notifier-0.1.5/app/views/shared/_frontend_notifier.html.haml (0.6ms)
    6605 I, [2015-08-19T22:39:16.943135 #4646]  INFO -- :   Rendered shared/_pre_load_images.html.haml (1.0ms)
    6606 I, [2015-08-19T22:39:16.944586 #4646]  INFO -- :   Rendered shared/_user_session.html.haml (0.4ms)
    6607 I, [2015-08-19T22:39:16.944690 #4646]  INFO -- :   Rendered layouts/_header.html.haml (1.4ms)
    6608 I, [2015-08-19T22:39:16.945281 #4646]  INFO -- :   Rendered shared/_email.html.erb (0.1ms)
    6609 I, [2015-08-19T22:39:16.945374 #4646]  INFO -- :   Rendered layouts/_footer.html.haml (0.5ms)
    6610 I, [2015-08-19T22:39:16.945556 #4646]  INFO -- :   Rendered shared/_google_analytics.html.erb (0.0ms)
    6611 I, [2015-08-19T22:39:16.945969 #4646]  INFO -- : Completed 200 OK in 25ms (Views: 23.5ms | ActiveRecord: 0.0ms)

**Comment by billy-ran-away** [comment]
@snitko this sounds similar to my issue #78...

**Comment by snitko** [comment]
@billy-ran-away I feel like this is related, but I can't make sense of it.
@jwg2s please note there's a bounty and I'm actually quite willing to pay for this issue to be resolved.

**Comment by jwg2s** [comment]
@sferik can you comment?  This issue is extremely problematic for us.  Any help would be greatly appreciated!

**Comment by snitko** [comment]
Going to close this issue. I discovered the problem and it was on my side: had a field which only validated on production and that caused `github()` action to silently redirect because there were no errors with authentication itself.

**Comment by jwg2s** [comment]
@snitko what was the field that was causing this issue?  We are still struggling to identify the cause

**Comment by snitko** [comment]
@jwg2s it was just a field in the model to which there was a validation and that validation was only enabled in production. So, my advice is, perhaps, to check whether you have any validation errors in the model.
