### ISSUE TITLE
Compatibility with omniauth >=1.3?

### ISSUE THREAD

**Issue by nikdavis** [intridea/omniauth-oauth2#87]
Is there any plan around this? It looks like you depend strictly on 1.2 at the moment. I haven't tried 1.3 with this gem, but it seems many folks are moving that way.

Thanks!

**Comment by wjordan** [comment]
The current [`"~> 1.2"`](https://github.com/intridea/omniauth-oauth2/blob/38222f8cd22de11d39022918f7c74a2f6df7fd3c/omniauth-oauth2.gemspec#L7) version constraint means "highest-released version between the range `>= 1.2` and `< 2.0`", which should already be compatible with version 1.3 of omniauth.

**Comment by nikdavis** [comment]
Agreed. Will close.
